[package]
name = "specification"
description = "heyhey"
url = ""
github = ""
shortName = ""
version = "0.1.0"
authors = ["David Wong <davidwg@calibra.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] } # deserialize toml
toml = "0.5" # deserialize toml
askama = "0.10"     # HTML template
clap = "2.33" # CLI
comrak = "0.9" # markdown
