[package]
name = "specification"
description = "heyhey"
url = ""
github = ""
shortName = ""
version = "0.1.0"
authors = ["David Wong <davidwg@calibra.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
askama = "0.10"     # to print the result as HTML
clap = "2.33"
