name: Deploy to Github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: produce spec
        run: |
          cargo run -- --output-format respec
          mkdir dist
          mv specification.html dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
